In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [5]:
print("1D Array")
a = np.array([1,2,3,4,5])
a

1D Array


array([1, 2, 3, 4, 5])

In [7]:
print("2D Array")
b = np.array([[1,2,3,4,5],
            [2,3,4,5,6]])
b

2D Array


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [11]:
print("3D Array")
c = np.array([[[1,2,3,4,5],
            [2,3,4,5,6],
             [3,4,5,6,7]]])
c

3D Array


array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [14]:
type(c)

numpy.ndarray

In [18]:
#Showing the len of the element
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [19]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [21]:
print(a.dtype)
print(b.dtype)
print(c.dtype)


int64
int64
int64


In [26]:
d = np.array([[1.5,2,3,4,5],
            [2,3,4,5,6],
             [3,4,5,6,7]])
print(d.dtype)

float64


In [23]:
d.transpose()

array([[[1.5],
        [2. ],
        [3. ]],

       [[2. ],
        [3. ],
        [4. ]],

       [[3. ],
        [4. ],
        [5. ]],

       [[4. ],
        [5. ],
        [6. ]],

       [[5. ],
        [6. ],
        [7. ]]])