In [1]:
import numpy as np

In [11]:
np.empty((4,4),dtype=int)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [6]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [9]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.zeros((2,5),dtype=bool)


array([[False, False, False, False, False],
       [False, False, False, False, False]])